on: [ push, pull_request ]
name: Build
jobs:
  build:
    strategy:
      matrix:
        go-version: [ 1.24.x ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v4
      - run: ./build.sh
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  release:
    name: Release binaries
    needs: [ build ]
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - name: Create Release and Attach Binaries
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          githubref=${{ github.ref }}
          version="${githubref##*/}"
          gh release create "${version}" -t "${version}" "./dist/*"
